/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user; sends an email verification code. */
        post: operations["registerUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Redeem an email verification code, activating the account. */
        post: operations["verifyEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/resend-verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reissue an email verification code. */
        post: operations["resendVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange credentials for an access/refresh token pair. */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange a refresh token for a new access/refresh pair. Refresh tokens are single-use — rotated on every call, the old one is invalidated the instant this succeeds. */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Invalidate a refresh token. Requires a valid access token. */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request a password reset code. Always returns the same response whether or not the email is registered, to avoid leaking account existence. */
        post: operations["forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Redeem a password reset code and set a new password. */
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The caller's own account, including its current ledger balance. */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transfers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The caller's own transfer history (sent and received), newest first. */
        get: operations["listTransfers"];
        put?: never;
        /** Create a transfer from the caller's own account to a recipient identified by account_number. sender_account_id is never taken from the request body — it's derived from the bearer token. */
        post: operations["createTransfer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deposits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a Stripe-funded top-up: creates a pending deposit and a matching Stripe PaymentIntent, returning its client_secret for Stripe.js/Elements to confirm directly with Stripe. account_id is never taken from the request body — it's derived from the bearer token. A successful client-side confirmPayment does NOT mean the deposit is credited yet — see GET /deposits/{id}. */
        post: operations["createDeposit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deposits/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Poll a deposit's status. 'succeeded' means Stripe confirmed the card charge; it does NOT mean the balance moved yet. 'credited' is the only status that means the ledger actually reflects it — the frontend must poll until 'credited' (or 'failed'), never stop at 'succeeded'. */
        get: operations["getDeposit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @example {
         *       "error": "invalid credentials"
         *     }
         */
        Error: {
            error: string;
            /** @description Only present on /auth/verify-email wrong-code responses — the number of guesses left before the code is locked out. */
            attempts_remaining?: number;
        };
        /**
         * @example {
         *       "status": "active"
         *     }
         */
        StatusResponse: {
            status: string;
        };
        MessageResponse: {
            message: string;
        };
        EmailRequest: {
            /** Format: email */
            email: string;
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        VerifyEmailRequest: {
            /** Format: email */
            email: string;
            /** @description 6-digit numeric code, expires 10 minutes after issue. */
            code: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        TokenPair: {
            /** @description JWT, 15 minute TTL. */
            access_token: string;
            /** @description Opaque, single-use, 7 day TTL. Rotated on every /auth/refresh call — the previous value stops working the instant a new one is issued. */
            refresh_token: string;
        };
        RefreshRequest: {
            refresh_token: string;
        };
        ResetPasswordRequest: {
            /** Format: email */
            email: string;
            code: string;
            new_password: string;
        };
        AccountWithBalance: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            user_id: string;
            account_number: string;
            /** @enum {string} */
            status: "active" | "frozen" | "closed";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /**
             * Format: int64
             * @description Minor units (cents). Formatting ("123.45 €") is the frontend's job, not the API's.
             */
            balance: number;
            /** @example EUR */
            currency: string;
        };
        CreateTransferRequest: {
            recipient_account_number: string;
            /**
             * Format: int64
             * @description Minor units (cents), must be positive.
             */
            amount: number;
        };
        Transfer: {
            /** Format: uuid */
            id: string;
            idempotency_key: string;
            /** Format: uuid */
            sender_account_id: string;
            /** Format: uuid */
            recipient_account_id: string;
            /** Format: int64 */
            amount: number;
            /** @enum {string} */
            status: "pending" | "completed" | "failed" | "rejected";
            /** @description Two disjoint vocabularies depending on status: a ledger failure code when status is "failed" (e.g. "insufficient_funds", "account_not_found", "invalid_amount", "ledger_internal_error"), or fraud-svc's triggered rule name when status is "rejected" ("amount_threshold", "velocity_count", "velocity_sum"). The two statuses are mutually exclusive, so which vocabulary applies is never ambiguous. */
            failure_reason?: string;
            /**
             * Format: uuid
             * @description Only present when status is completed.
             */
            ledger_transaction_id?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        TransferResult: components["schemas"]["Transfer"] & {
            /** @description Only present when the outcome is uncertain (202) — e.g. "transfer status unknown, still processing". */
            message?: string;
        };
        CreateDepositRequest: {
            /**
             * Format: int64
             * @description Minor units (cents). Bounded server-side to €0.50–€10,000.00 (services/transfers-svc/deposit.go's depositMinAmount/ depositMaxAmount).
             */
            amount: number;
        };
        CreateDepositResponse: {
            /** Format: uuid */
            deposit_id: string;
            /** @description Stripe PaymentIntent client_secret — hand this to Stripe.js/Elements to confirm the payment directly with Stripe. Never reuse across a retry after a decline: a new attempt means a new POST /deposits call and a new client_secret. */
            client_secret: string;
        };
        Deposit: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            account_id: string;
            /** Format: int64 */
            amount: number;
            /** @example eur */
            currency: string;
            /**
             * @description 'succeeded' means Stripe confirmed the card charge only. 'credited' means the ledger balance actually reflects it — the status pollers must wait for. 'refunded' is only reachable from 'credited' (a charge.refunded event after this service already credited it); a poller that hasn't already stopped at 'credited' should treat 'refunded' as terminal too.
             * @enum {string}
             */
            status: "pending" | "succeeded" | "credited" | "failed" | "refunded";
            stripe_payment_intent_id?: string;
            /** Format: uuid */
            ledger_transaction_id?: string;
            failure_reason?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /** @description Despite the name (kept for compatibility with the /transfers path and this field's existing key), this is the caller's UNIFIED operations feed — transfers, deposits, and withdrawals interleaved newest-first — not transfers alone. See services/transfers-svc/history.go's historyEntry doc comment. */
        TransferHistoryPage: {
            transfers: components["schemas"]["TransferHistoryEntry"][];
            /** @description Pass as ?cursor= on the next request. Absent when there are no more pages. */
            next_cursor?: string;
        };
        TransferHistoryEntry: {
            /** @enum {string} */
            type: "transfer" | "deposit" | "withdrawal";
            /** Format: uuid */
            id: string;
            /**
             * Format: int64
             * @description Minor units (cents).
             */
            amount: number;
            /** @description Vocabulary depends on type: transfer is one of [pending, completed, failed, rejected]; deposit is one of [pending, succeeded, credited, failed, refunded]; withdrawal is one of [payout_simulated, failed]. */
            status: string;
            failure_reason?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /**
             * @description transfer only — absent for deposit/withdrawal entries.
             * @enum {string}
             */
            direction?: "outgoing" | "incoming";
            /** @description transfer only — absent for deposit/withdrawal entries. */
            counterparty_account_number?: string;
        };
    };
    responses: {
        /** @description Malformed request body or invalid field value. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing, invalid, or expired bearer token. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Rate-limited; wait before retrying. */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unexpected server error. */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    registerUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Registration accepted, pending email verification. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Email already registered to an active or suspended user. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    verifyEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmailRequest"];
            };
        };
        responses: {
            /** @description Account activated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            /** @description Invalid body, unknown user, no active code, expired code, too many failed attempts, or wrong code — all reported the same way to keep this response uniform. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    resendVerification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailRequest"];
            };
        };
        responses: {
            /** @description A new code was sent. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Invalid email or password. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Credentials are correct but the email isn't verified yet. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description New token pair issued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Refresh token is invalid, expired, already used, or the account is no longer active. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Logged out. Returned even if the refresh token was already invalid or missing — logout is deliberately lenient. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailRequest"];
            };
        };
        responses: {
            /** @description Uniform response, regardless of whether the email exists. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description Password changed; all existing sessions were revoked. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            /** @description Invalid body, password too short, or an invalid/expired/ already-used reset code — all reported the same way, for the same enumeration-avoidance reason as /auth/forgot-password. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Account and balance. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountWithBalance"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description No account exists for this user. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalError"];
            /** @description ledger-svc is temporarily unreachable. Deliberately not a 200 with a zero balance — a fake zero is worse than an honest "unavailable" in a banking product. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listTransfers: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Opaque continuation token from a previous response's next_cursor. Omit to fetch the first page. */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of transfer history. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransferHistoryPage"];
                };
            };
            /** @description Malformed cursor. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description The caller has no account yet. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    createTransfer: {
        parameters: {
            query?: never;
            header: {
                /** @description Client-generated UUID for this transfer attempt. Retrying the exact same attempt (network failure, no response received) must reuse the same key; a genuinely new transfer needs a new one. */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTransferRequest"];
            };
        };
        responses: {
            /** @description A transfer with this Idempotency-Key already existed — its current state is returned as-is, without moving money again. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransferResult"];
                };
            };
            /** @description A definite outcome was reached (completed, failed, or rejected). */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransferResult"];
                };
            };
            /** @description The outcome is uncertain and the transfer is left pending. Two distinct causes share this same shape (TransferResult with status "pending" and a message) with no separate discriminator field — callers must match on message text: ledger-svc did not respond definitively ("transfer status unknown, still processing"), or fraud-svc was unreachable and the check fails closed ("fraud check unavailable, transfer still pending"). */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransferResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Recipient not found, or the caller has no account yet. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Recipient account is closed, or sender account is not active. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Idempotency-Key was already used with different parameters. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    createDeposit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDepositRequest"];
            };
        };
        responses: {
            /** @description Pending deposit created and a Stripe PaymentIntent started. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateDepositResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description The caller has no account yet. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Account is not active. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    getDeposit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The deposit's current state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deposit"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description No such deposit, or it belongs to a different account — deliberately indistinguishable, so this endpoint can never be used to enumerate another account's deposit ids. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
}
