package main

import (
	"context"
	"encoding/csv"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

// k6Summary mirrors the compact object k6/common.js's handleSummary
// writes. It is deliberately a small fixed shape rather than k6's own
// summary dump: see that function's comment for why.
type k6Summary struct {
	Profile          string           `json:"profile"`
	VUs              int              `json:"vus"`
	DurationS        float64          `json:"duration_s"`
	Iterations       int64            `json:"iterations"`
	HTTPReqs         int64            `json:"http_reqs"`
	RPS              float64          `json:"rps"`
	SettledPerS      float64          `json:"settled_per_s"`
	LatencyMS        *latencyStats    `json:"latency_ms"`
	SettledLatencyMS *latencyStats    `json:"settled_latency_ms"`
	Outcomes         map[string]int64 `json:"outcomes"`
	ErrorRate        float64          `json:"error_rate"`
}

type latencyStats struct {
	Avg float64 `json:"avg"`
	P50 float64 `json:"p50"`
	P90 float64 `json:"p90"`
	P95 float64 `json:"p95"`
	P99 float64 `json:"p99"`
	Max float64 `json:"max"`
}

func runReport(_ context.Context, args []string) error {
	fs := flag.NewFlagSet("report", flag.ExitOnError)
	dir := fs.String("results", "loadtest/results", "directory holding the k6 summaries, probe CSVs and verify reports")
	out := fs.String("out", "loadtest/results/REPORT.md", "Markdown output path")
	if err := fs.Parse(args); err != nil {
		return err
	}

	summaryPaths, err := filepath.Glob(filepath.Join(*dir, "*.summary.json"))
	if err != nil {
		return err
	}
	if len(summaryPaths) == 0 {
		return fmt.Errorf("no *.summary.json in %s — run a profile first", *dir)
	}

	summaries := make([]k6Summary, 0, len(summaryPaths))
	for _, p := range summaryPaths {
		data, err := os.ReadFile(p)
		if err != nil {
			return err
		}
		var s k6Summary
		if err := json.Unmarshal(data, &s); err != nil {
			return fmt.Errorf("parse %s: %w", p, err)
		}
		summaries = append(summaries, s)
	}
	// Group by profile, ascending VU level inside each: the table is read
	// down a column to see how one profile responds to concurrency, which
	// only works if the levels are in order.
	sort.Slice(summaries, func(i, j int) bool {
		if summaries[i].Profile != summaries[j].Profile {
			return summaries[i].Profile < summaries[j].Profile
		}
		return summaries[i].VUs < summaries[j].VUs
	})

	var b strings.Builder
	b.WriteString("# Load-test results\n\n")
	b.WriteString("Generated by `lt report`. Latency is the full `POST /transfers` round trip through the gateway.\n\n")

	b.WriteString("## Throughput and latency\n\n")
	b.WriteString("| profile | VUs | RPS | settled/s | p50 | p95 | p99 | max | errors |\n")
	b.WriteString("|---|---:|---:|---:|---:|---:|---:|---:|---:|\n")
	for _, s := range summaries {
		l := s.LatencyMS
		if l == nil {
			l = &latencyStats{}
		}
		fmt.Fprintf(&b, "| %s | %d | %.1f | %.1f | %.0f ms | %.0f ms | %.0f ms | %.0f ms | %.2f%% |\n",
			s.Profile, s.VUs, s.RPS, s.SettledPerS, l.P50, l.P95, l.P99, l.Max, s.ErrorRate*100)
	}

	b.WriteString("\n## Outcome breakdown\n\n")
	b.WriteString("`completed` moved money. `rejected` is fraud-svc, `failed` is ledger-svc, `replayed` is an idempotent hit (HTTP 200), ")
	b.WriteString("`uncertain` is a 202 — the transfer is parked pending for reconciliation. Only `server_error` and `transport_error` count toward the error rate.\n\n")
	b.WriteString("| profile | VUs | completed | rejected | failed | replayed | uncertain | 401 | client err | server err | transport err |\n")
	b.WriteString("|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|\n")
	for _, s := range summaries {
		o := s.Outcomes
		fmt.Fprintf(&b, "| %s | %d | %d | %d | %d | %d | %d | %d | %d | %d | %d |\n",
			s.Profile, s.VUs, o["completed"], o["rejected"], o["failed"], o["replayed"],
			o["uncertain"], o["unauthorized"], o["client_error"], o["server_error"], o["transport_error"])
	}
	// A non-zero 401 column means the fixture tokens expired part-way
	// through and everything after that point is noise. Called out in the
	// report rather than left to be spotted in a column, because the
	// symptom (throughput up, error rate zero) reads as a good run.
	for _, s := range summaries {
		if s.Outcomes["unauthorized"] > 0 {
			fmt.Fprintf(&b, "\n> **%s @ %d VUs is INVALID**: %d requests were answered 401 — the fixture tokens expired mid-run. Reissue with `lt setup -refresh` and re-run.\n",
				s.Profile, s.VUs, s.Outcomes["unauthorized"])
		}
	}

	probeSection, err := renderProbeSection(*dir)
	if err != nil {
		return err
	}
	b.WriteString(probeSection)

	verifySection, err := renderVerifySection(*dir)
	if err != nil {
		return err
	}
	b.WriteString(verifySection)

	if err := os.MkdirAll(filepath.Dir(*out), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(*out, []byte(b.String()), 0o644); err != nil {
		return err
	}
	fmt.Printf("report: wrote %s (%d runs)\n", *out, len(summaries))
	return nil
}

// renderProbeSection reduces each probe CSV to the peaks. Peaks, not
// averages: a connection pool that sat at its ceiling for ten seconds of a
// sixty-second run has an unremarkable mean and is exactly where the p99
// came from.
func renderProbeSection(dir string) (string, error) {
	paths, err := filepath.Glob(filepath.Join(dir, "*.probe.csv"))
	if err != nil {
		return "", err
	}
	if len(paths) == 0 {
		return "", nil
	}
	sort.Strings(paths)

	var b strings.Builder
	b.WriteString("\n## What Postgres saw (peaks during each run)\n\n")
	b.WriteString("`outbox` is reported as start→end rather than as a peak: the backlog is cumulative across runs on a stack ")
	b.WriteString("whose relay never catches up, so how far it GREW during a run is the number that means something, and an ")
	b.WriteString("absolute peak would mostly report how much was already there. `longest txn` is the oldest open transaction ")
	b.WriteString("seen at any sample — the outbox relay holds one for the length of a whole batch.\n\n")
	b.WriteString("| run | conns max | active max | lock waiters max | ungranted locks max | outbox start→end | pending max | longest txn | replica lag max |\n")
	b.WriteString("|---|---:|---:|---:|---:|---:|---:|---:|---:|\n")

	for _, p := range paths {
		peaks, err := probePeaks(p)
		if err != nil {
			return "", err
		}
		if peaks == nil {
			continue
		}
		first, last, err := probeEndpoints(p, "outbox_backlog")
		if err != nil {
			return "", err
		}
		name := strings.TrimSuffix(filepath.Base(p), ".probe.csv")
		fmt.Fprintf(&b, "| %s | %.0f | %.0f | %.0f | %.0f | %.0f→%.0f (%+.0f) | %.0f | %.0fs | %.0f B |\n",
			name, peaks["conns_total"], peaks["conns_active"], peaks["lock_waiters"],
			peaks["locks_ungranted"], first, last, last-first, peaks["transfers_pending"],
			peaks["longest_txn_seconds"], peaks["replica_lag_bytes"])
	}
	return b.String(), nil
}

// probeEndpoints returns a column's first and last sampled value, which is
// what turns a cumulative counter like the outbox backlog into a delta.
func probeEndpoints(path, column string) (first, last float64, err error) {
	f, err := os.Open(path)
	if err != nil {
		return 0, 0, err
	}
	defer f.Close()

	records, err := csv.NewReader(f).ReadAll()
	if err != nil {
		return 0, 0, fmt.Errorf("read %s: %w", path, err)
	}
	if len(records) < 2 {
		return 0, 0, nil
	}
	idx := -1
	for i, name := range records[0] {
		if name == column {
			idx = i
			break
		}
	}
	if idx < 0 {
		return 0, 0, fmt.Errorf("%s has no column %q", path, column)
	}
	parse := func(row []string) float64 {
		if idx >= len(row) {
			return 0
		}
		v, err := strconv.ParseFloat(row[idx], 64)
		if err != nil {
			return 0
		}
		return v
	}
	return parse(records[1]), parse(records[len(records)-1]), nil
}

func probePeaks(path string) (map[string]float64, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	records, err := csv.NewReader(f).ReadAll()
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", path, err)
	}
	if len(records) < 2 {
		return nil, nil
	}
	header := records[0]
	peaks := map[string]float64{}
	for _, row := range records[1:] {
		for i, col := range header {
			if i >= len(row) {
				continue
			}
			v, err := strconv.ParseFloat(row[i], 64)
			if err != nil {
				continue
			}
			if v > peaks[col] {
				peaks[col] = v
			}
		}
	}
	return peaks, nil
}

func renderVerifySection(dir string) (string, error) {
	paths, err := filepath.Glob(filepath.Join(dir, "*.verify.json"))
	if err != nil {
		return "", err
	}
	if len(paths) == 0 {
		return "", nil
	}
	sort.Strings(paths)

	var b strings.Builder
	b.WriteString("\n## Invariants after each profile\n\n")
	for _, p := range paths {
		data, err := os.ReadFile(p)
		if err != nil {
			return "", err
		}
		var r struct {
			Profile string        `json:"profile"`
			Passed  bool          `json:"passed"`
			Checks  []checkResult `json:"checks"`
		}
		if err := json.Unmarshal(data, &r); err != nil {
			return "", fmt.Errorf("parse %s: %w", p, err)
		}
		verdict := "all hold"
		if !r.Passed {
			verdict = "**VIOLATED**"
		}
		fmt.Fprintf(&b, "### %s — %s\n\n", displayProfile(r.Profile), verdict)
		b.WriteString("| invariant | result | detail |\n|---|---|---|\n")
		for _, c := range r.Checks {
			mark := "pass"
			if !c.Passed {
				mark = "**FAIL**"
			}
			fmt.Fprintf(&b, "| `%s` | %s | %s |\n", c.Name, mark, c.Summary)
		}
		b.WriteString("\n")
	}
	return b.String(), nil
}
